// npm run build
//   app/rotation-tracker.html  ──patch──▶  dist/index.html
//   src/cloud.js (+ aws-amplify, amplify_outputs.json)  ──esbuild──▶  dist/cloud.js
//
// You can drop a fresh standalone export straight into app/rotation-tracker.html —
// the cloud hooks are (re)applied here. If an anchor ever stops matching, the build
// fails loudly instead of shipping a tracker that silently only saves locally.
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const args = Object.fromEntries(process.argv.slice(2).map((a) => a.replace(/^--/, '').split('=')));
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const SRC_HTML = path.join(ROOT, args.html || 'app/rotation-tracker.html');
const ENTRY = path.join(ROOT, args.entry || 'src/cloud.js');
const OUT = path.join(ROOT, args.out || 'dist');

// ---------- 1. hooks inside the bundled app (template JSON) ----------
const INNER = [
  [
    "    try { const s = localStorage.getItem(this.KEY); if (s){ const d = JSON.parse(s); if (d && d.workspaces) return this.ensure(d); } } catch(e){}\n",
    "    // Cloud (Amplify/DynamoDB) build: RTCloud loads the shared dataset before the app\n" +
    "    // mounts. Standalone file: RTCloud is absent and this falls through to localStorage.\n" +
    "    try { const c = window.RTCloud && window.RTCloud.initialData; if (c && c.workspaces) return this.ensure(c); } catch(e){}\n" +
    "    try { const s = localStorage.getItem(this.KEY); if (s){ const d = JSON.parse(s); if (d && d.workspaces) return this.ensure(d); } } catch(e){}\n",
  ],
  [
    "  save(data){ try { localStorage.setItem(this.KEY, JSON.stringify(data)); } catch(e){} }\n",
    "  save(data){ try { localStorage.setItem(this.KEY, JSON.stringify(data)); } catch(e){} if (window.RTCloud) window.RTCloud.save(data); }\n" +
    "  // Another manager saved: RTCloud hands us the merged dataset. setState directly\n" +
    "  // (not update()) so the change isn't echoed back to the cloud.\n" +
    "  componentDidMount(){ if (window.RTCloud) this._cloudOff = window.RTCloud.onRemote(d=>{ const data = this.ensure(d); try { localStorage.setItem(this.KEY, JSON.stringify(data)); } catch(e){} this.setState({ data }); }); }\n" +
    "  componentWillUnmount(){ if (this._cloudOff) this._cloudOff(); }\n",
  ],
];

// ---------- 2. outer page: load cloud.js, make the bundler wait for sign-in + data ----------
const LOADER_ANCHOR = "document.addEventListener('DOMContentLoaded', async function() {";
const LOADER_WAIT = LOADER_ANCHOR + "\n  if (window.RTCloud) { try { await window.RTCloud.ready; } catch (e) { return; } }";
const CLOUD_TAG = '<script src="./cloud.js"></script>';

const encodeTemplate = (t) => JSON.stringify(t).split('</').join('<\\u002F');
const count = (s, sub) => s.split(sub).length - 1;
function fail(msg) { console.error('\n✖ build: ' + msg + '\n'); process.exit(1); }

export function patchTracker(html) {
  const re = /(<script type="__bundler\/template">)([\s\S]*?)(<\/script>)/;
  const m = re.exec(html);
  if (!m) fail('no __bundler/template block found — is this a Rotation Tracker standalone export?');
  const raw = m[2];
  const lead = raw.slice(0, raw.length - raw.trimStart().length);
  const trail = raw.slice(raw.trimEnd().length);
  let tpl = JSON.parse(raw.trim());
  if (encodeTemplate(tpl) !== raw.trim()) fail('template encoding round-trip mismatch — refusing to re-encode');

  let innerApplied = 0;
  if (!tpl.includes('window.RTCloud')) {
    for (const [from, to] of INNER) {
      if (count(tpl, from) !== 1) fail('app hook anchor not found (or not unique):\n  ' + from.trim().slice(0, 90) + '…');
      tpl = tpl.replace(from, () => to);
      innerApplied++;
    }
  }
  const newTpl = encodeTemplate(tpl);
  if (JSON.parse(newTpl) !== tpl) fail('re-encoded template does not decode to the patched source');
  let out = html.slice(0, m.index) + m[1] + lead + newTpl + trail + m[3] + html.slice(m.index + m[0].length);

  if (!out.includes(CLOUD_TAG)) {
    if (count(out, '</head>') < 1) fail('no </head> in outer page');
    const i = out.indexOf('</head>');
    out = out.slice(0, i) + '  ' + CLOUD_TAG + '\n' + out.slice(i);
  }
  if (!out.includes('window.RTCloud.ready')) {
    if (count(out, LOADER_ANCHOR) !== 1) fail('bundler loader anchor not found');
    out = out.replace(LOADER_ANCHOR, () => LOADER_WAIT);
  }
  return { html: out, innerApplied };
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  if (!fs.existsSync(SRC_HTML)) fail('missing ' + SRC_HTML);
  if (!args.entry && !fs.existsSync(path.join(ROOT, 'amplify_outputs.json'))) {
    fail('amplify_outputs.json not found. In Amplify Hosting it is generated by the backend phase;\n' +
         '  locally run `npx ampx sandbox` (or `npx ampx generate outputs --app-id <id> --branch main`) first.');
  }
  fs.mkdirSync(OUT, { recursive: true });
  const { html, innerApplied } = patchTracker(fs.readFileSync(SRC_HTML, 'utf8'));
  fs.writeFileSync(path.join(OUT, 'index.html'), html);
  await build({
    entryPoints: [ENTRY], bundle: true, format: 'iife', minify: true, target: 'es2020',
    outfile: path.join(OUT, 'cloud.js'), logLevel: 'warning', legalComments: 'none',
  });
  const kb = (f) => (fs.statSync(path.join(OUT, f)).size / 1024).toFixed(0) + ' KB';
  console.log(`✔ dist/index.html (${kb('index.html')}, hooks ${innerApplied ? 'applied' : 'already present'})  dist/cloud.js (${kb('cloud.js')})`);
}
